<a href="https://colab.research.google.com/github/mariluvarela/LABORATORIOS-DE-PYTHON-MECANICA-CUANTICA-2026/blob/main/dos_estados_fase_py_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
h_partida = 1
m = 1
L = 1 # Longitud del pozo

# Definimos x para la evaluación de V_p, asumiendo un valor de ejemplo
x = 0.5 # Puedes cambiar este valor para probar diferentes casos

if 0 < x < L:
    V_p = 0
else:
    print(f"Para x={x}, V_p='infinito'")
    V_p = np.inf # Usar np.inf para representar infinito numéricamente

# Definimos N (número de puntos interiores)
N = 15 # Por ejemplo, 5 puntos interiores

# Calculamos Delta_x
Delta_x = L / (N + 1)

# Construimos los puntos interiores de la malla
# i = 1, 2, ..., N
mesh_points = []
for i in range(1, N + 1):
    point_val = i * Delta_x
    mesh_points.append(point_val)

print(f"Puntos interiores de la malla (x_i): {mesh_points}")
print(f"Valor de V_p para x={x}: {V_p}")

Puntos interiores de la malla (x_i): [0.0625, 0.125, 0.1875, 0.25, 0.3125, 0.375, 0.4375, 0.5, 0.5625, 0.625, 0.6875, 0.75, 0.8125, 0.875, 0.9375]
Valor de V_p para x=0.5: 0


### Construcción de la matriz del Hamiltoniano para el Pozo Cuadrado Infinito

El operador Hamiltoniano para una partícula en un pozo cuadrado infinito, cuando se discretiza utilizando diferencias finitas para la segunda derivada, produce una matriz **tridiagonal**. La ecuación de Schrödinger independiente del tiempo es:

$$- \frac{\hbar^2}{2m} \frac{d^2\psi}{dx^2} + V(x)\psi = E\psi$$

Sustituyendo la aproximación de la segunda derivada (`deriv_ir` donde $\psi$ es $\Phi$ y $\hbar$ es `h_partida`):

$$- \frac{\text{h_partida}^2}{2m} \frac{\Phi_{i+1} - 2\Phi_i + \Phi_{i-1}}{\Delta x^2} + V_i\Phi_i = E\Phi_i$$

Dentro del pozo, $V_i = 0$. Reorganizando para obtener los coeficientes de $\Phi_{i-1}$, $\Phi_i$, y $\Phi_{i+1}$:

$$-\frac{\text{h_partida}^2}{2m\Delta x^2}\Phi_{i-1} + \left(\frac{\text{h_partida}^2}{m\Delta x^2}\right)\Phi_i - \frac{\text{h_partida}^2}{2m\Delta x^2}\Phi_{i+1} = E\Phi_i$$

Esto forma una matriz tridiagonal donde los elementos son:
-   **Diagonal principal**: $$\frac{\text{h_partida}^2}{m\Delta x^2}$$ (a veces escrito como $$\frac{2C}{\Delta x^2}$$ donde C es una constante que incluye $\hbar^2/2m$)
-   **Diagonales superior e inferior**: $$-\frac{\text{h_partida}^2}{2m\Delta x^2}$$

Generación de la matriz tri-diagonal.

In [ ]:
import numpy as np

# Recuperamos los valores de las celdas anteriores
# h_partida = 1 (hbar)
# m = 1 (masa)
# L = 1 (longitud del pozo)
# N = 10 (número de puntos interiores) # Usamos N=5 como está definido en P1PYIkqdIpwt
# Delta_x = L / (N + 1)

# Como se solicita, calculamos la matriz sin el factor h_partida**2 / (2 * m * Delta_x**2)
# Los elementos de la matriz serán 2 en la diagonal principal y -1 en las diagonales laterales.

diagonal_principal_val = 2
diagonal_lateral_val = -1

# Creamos la matriz tridiagonal de tamaño N x N
Hamiltonian_matrix = np.zeros((N, N))

# Llenar la diagonal principal
np.fill_diagonal(Hamiltonian_matrix, diagonal_principal_val)

# Llenar la diagonal superior (k=1)
np.fill_diagonal(Hamiltonian_matrix[0:, 1:], diagonal_lateral_val)

# Llenar la diagonal inferior (k=-1)
np.fill_diagonal(Hamiltonian_matrix[1:, 0:], diagonal_lateral_val)

print(f"Matriz Hamiltoniana (Tridiagonal) sin factor de escala para N={N} puntos:")
print(Hamiltonian_matrix)


Matriz Hamiltoniana (Tridiagonal) sin factor de escala para N=15 puntos:
[[ 2. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  2. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  2. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  2. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  2. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  2. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  2. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  2. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  2. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  2. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  2. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  2. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  2. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  2. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.

In [ ]:
Fi(0)=0
Fi=(N+1)=0
N=50
deriv_ir=(Fi(i+1) - 2 * Fi(i) + Fi(i-1))/(Delta_x**2)

In [ ]:
variable_entera = 10
variable_flotante = 20.5
variable_cadena = "Hola"
variable_booleana = True

print(f"Entero: {variable_entera}")
print(f"Flotante: {variable_flotante}")
print(f"Cadena: {variable_cadena}")
print(f"Booleano: {variable_booleana}")


Función de pozo cuadrado infinito.

### Sintaxis de la sentencia `if` en Python

La estructura básica de una sentencia `if` en Python para tomar decisiones es la siguiente:

```python
if condicion:
    # Código a ejecutar si la condición es verdadera
elif otra_condicion:
    # Código a ejecutar si la primera condición es falsa y esta es verdadera
else:
    # Código a ejecutar si ninguna de las condiciones anteriores es verdadera
```

**Puntos clave:**
-   **`if`**: La palabra clave `if` inicia la sentencia, seguida de una condición.
-   **`condicion`**: Una expresión que se evalúa como `True` o `False`.
-   **Dos puntos (`:`)**: Siempre debe terminar la línea de la condición con dos puntos.
-   **Indentación**: El código dentro del bloque `if`, `elif` o `else` debe estar indentado (generalmente con 4 espacios) para indicar que pertenece a ese bloque.
-   **`elif` (opcional)**: Significa "else if" y permite comprobar múltiples condiciones. Puedes tener cero o varias cláusulas `elif`.
-   **`else` (opcional)**: La cláusula `else` se ejecuta si ninguna de las condiciones `if` o `elif` anteriores es verdadera. Solo puede haber una cláusula `else`.

In [ ]:
# Ejemplo de uso de la sentencia if

edad = 20

if edad < 18:
    print("Eres menor de edad.")
elif edad >= 18 and edad < 65:
    print("Eres un adulto.")
else:
    print("Eres una persona mayor.")

# Ahora aplicando la lógica que mencionaste (0 < x < L)
# Usaremos las variables 'x' y 'L' que ya están definidas en el cuaderno.

# Probemos con un valor de x dentro del rango
x_test_dentro = 0.5
if 0 < x_test_dentro < L:
    V_p_valor = 0
    print(f"Para x = {x_test_dentro}, V_p = {V_p_valor}")
else:
    print(f"Para x = {x_test_dentro}, V_p = 'infinito'")

# Probemos con un valor de x fuera del rango
x_test_fuera = 1.2
if 0 < x_test_fuera < L:
    V_p_valor = 0
    print(f"Para x = {x_test_fuera}, V_p = {V_p_valor}")
else:
    print(f"Para x = {x_test_fuera}, V_p = 'infinito'")

In [ ]:
import numpy as np

# Definimos N (número de puntos interiores)
N = 5 # Por ejemplo, 5 puntos interiores

# Calculamos Delta_x
Delta_x = L / (N + 1)
print(f"Delta_x = {Delta_x}")

# Construimos los puntos interiores de la malla
# i = 1, 2, ..., N

x_puntos = []
for i in range(1, N + 1):
    x_i = i * Delta_x
    x_puntos.append(x_i)

print(f"Puntos interiores de la malla (x_i): {x_puntos}")

# También podemos usar numpy para una generación más eficiente:
x_puntos_np = np.linspace(Delta_x, L - Delta_x, N)
print(f"Puntos interiores de la malla (usando numpy): {x_puntos_np}")

### Construyendo la malla espacial

Primero, definimos el número de puntos interiores (`N`) para nuestra malla. Luego, calculamos `Delta_x`, que es la distancia entre cada punto de la malla. Finalmente, generamos los puntos `x_i` que forman la malla.

In [ ]:
import numpy as np

# Definimos N (número de puntos interiores)
N = 5 # Por ejemplo, 5 puntos interiores

# Calculamos Delta_x
Delta_x = L / (N + 1)
print(f"Delta_x = {Delta_x}")

# Construimos los puntos interiores de la malla
# i = 1, 2, ..., N

x_puntos = []
for i in range(1, N + 1):
    x_i = i * Delta_x
    x_puntos.append(x_i)

print(f"Puntos interiores de la malla (x_i): {x_puntos}")

# También podemos usar numpy para una generación más eficiente:
x_puntos_np = np.linspace(Delta_x, L - Delta_x, N)
print(f"Puntos interiores de la malla (usando numpy): {x_puntos_np}")

# Let's assume 'x' and 'L' are already defined, for example:
x = 0.7
# L is already defined as 1 in the previous cell

resultado = None # Initialize resultado

if 0 < x < L:
    resultado = 0
    print(f"Dado que 0 < {x} < {L}, 'resultado' es: {resultado}")
else:
    print(f"La condición 0 < {x} < {L} no se cumple. 'resultado' sigue siendo: {resultado}")

# Example with a different 'x' where the condition is not met
x_fuera_rango = 1.5
if 0 < x_fuera_rango < L:
    resultado_fuera = 0
    print(f"Dado que 0 < {x_fuera_rango} < {L}, 'resultado_fuera' es: {resultado_fuera}")
else:
    resultado_fuera = "No cumple"
    print(f"La condición 0 < {x_fuera_rango} < {L} no se cumple. 'resultado_fuera' es: {resultado_fuera}")

### Representing chained inequalities

To express a condition like `0 < x < L` in Python, you have two primary options:

1.  **Using `and` operator**: Combine two separate conditions with `and`. For example, `0 < x and x < L`.
2.  **Chained comparison operators**: Python allows you to directly chain comparison operators, which is often more concise and readable. For example, `0 < x < L`.

In [ ]:
# As an example, let's test a value for 'x'
x_valor = 0.5

# Using the 'and' operator
condicion_and = (0 < x_valor) and (x_valor < L)
print(f"Usando 'and': ¿0 < {x_valor} < {L}? {condicion_and}")

# Using chained comparison operators (more Pythonic and readable)
condicion_encadenada = 0 < x_valor < L
print(f"Usando encadenamiento: ¿0 < {x_valor} < {L}? {condicion_encadenada}")

# Let's test another value for 'x' outside the range
x_valor_fuera = 1.2
condicion_fuera = 0 < x_valor_fuera < L
print(f"Usando encadenamiento: ¿0 < {x_valor_fuera} < {L}? {condicion_fuera}")

### Defining a function by parts

To define a function "by parts," you can break down a complex task into several smaller, more manageable functions. Each smaller function handles a specific sub-task, and then a main function orchestrates the calls to these sub-functions.

This approach helps in:
- **Modularity**: Each part is a self-contained unit.
- **Readability**: Easier to understand what each part of the code does.
- **Reusability**: Smaller functions can often be reused in different contexts.
- **Debugging**: Easier to isolate and fix issues in smaller units.

In [ ]:
def sumar_dos_numeros(a, b):
    # Parte 1: Suma de dos números
    resultado_suma = a + b
    return resultado_suma

def multiplicar_por_factor(numero, factor):
    # Parte 2: Multiplica un número por un factor
    resultado_multiplicacion = numero * factor
    return resultado_multiplicacion

def realizar_calculo_complejo(num1, num2, factor):
    # Función principal que usa las "partes"

    # Paso 1: Sumar los números
    suma = sumar_dos_numeros(num1, num2)
    print(f"Paso 1: La suma de {num1} y {num2} es: {suma}")

    # Paso 2: Multiplicar el resultado de la suma por un factor
    resultado_final = multiplicar_por_factor(suma, factor)
    print(f"Paso 2: El resultado de multiplicar {suma} por {factor} es: {resultado_final}")

    return resultado_final

# Demostración del uso de la función "por partes"
numero1 = 5
numero2 = 3
mi_factor = 2

print("\n--- Ejecutando cálculo complejo ---")
final = realizar_calculo_complejo(numero1, numero2, mi_factor)
print(f"Resultado final del cálculo complejo: {final}")